import { Activity, CalendarDays, Dumbbell, UserCog } from 'lucide-react'
import type { Student } from '../../types'
import { dayNames } from '../../lib/dates'
import { faNumber } from '../../lib/numbers'

export function PublicProgramPage({ student }: { student: Student }) {
  const program = student.program
  const sentAt = program.sentAt ? new Date(program.sentAt) : new Date()
  return <main className="public-program-page"><header className="public-program-header"><div className="login-brand"><div className="brand-mark"><Activity/></div><strong>شاگردیتو</strong></div><span>برنامه تمرینی اختصاصی</span></header><section className="public-program-hero"><div><small>برنامه اختصاصی برای</small><h1>{student.name}</h1><p>{student.goal}</p><div className="public-meta"><span><UserCog size={16}/> مربی: {program.coachName || 'مهدی حسینی'}</span><span><CalendarDays size={16}/> ارسال شده در {new Intl.DateTimeFormat('fa-IR', { day: 'numeric', month: 'long', year: 'numeric' }).format(sentAt)}</span></div></div><div className="public-badge"><Dumbbell/><span>{faNumber(program.days.length)} جلسه در هفته</span></div></section><section className="public-program-content"><div className="public-program-title"><div><span>برنامه فعال</span><h2>{program.title}</h2></div><div className="public-plan-chip">نسخه اشتراکی</div></div><div className="public-days">{program.days.map((day, index) => <article className="public-day-card" key={day.id}><div className="public-day-top"><div className="day-number">{faNumber(index + 1)}</div><div><small>{dayNames[day.dayIndex]}</small><h3>{day.title}</h3></div><span>{faNumber(day.exercises.length)} حرکت</span></div><div className="public-exercises">{day.exercises.map(exercise => <div key={exercise.id}><span><b>{exercise.name}</b>{exercise.note && <small>{exercise.note}</small>}</span><strong>{faNumber(exercise.sets)} ست × {exercise.reps}{exercise.targetWeight ? ` · ${exercise.targetWeight.toLocaleString('fa-IR')} ک‌گ` : ''}</strong></div>)}</div></article>)}</div><footer className="public-program-footer"><Activity size={18}/><span>این برنامه در شاگردیتو ساخته شده و فقط برای شما قابل مشاهده است.</span></footer></section></main>
}
