export type Page = 'dashboard' | 'students' | 'inbox' | 'settings' | 'profile'
export type ClientPage = 'home' | 'plan' | 'workout' | 'feedback' | 'progress' | 'checkin'
export type ProfileTab = 'overview' | 'program' | 'progress' | 'checkins' | 'timeline' | 'finance' | 'assistant'
export type UserRole = 'coach' | 'admin'

export type { CheckIn } from './domain/checkins/types'
export type { TimelineItem } from './domain/timeline/types'
export type { ExercisePrescription, WorkoutDay, WeeklyProgram, ExerciseResult, WorkoutLog } from './domain/training/types'
export type { PaymentRecord } from './domain/payments/types'
export type { Student, Measurement } from './domain/student/types'
export type { StudentStatus, Signal, StudentAnalysis } from './domain/attention/types'
