import { useState } from 'react'
import { ArrowLeft, Check } from 'lucide-react'
import type { ExerciseResult, WorkoutDay } from '../../types'
import { faNumber } from '../../lib/numbers'

export function ClientWorkout({ day, review }: { day: WorkoutDay; review: (results: ExerciseResult[]) => void }) {
  const [results, setResults] = useState(() => day.exercises.map(exercise => ({ exerciseId: exercise.id, exerciseName: exercise.name, completed: false, actualWeight: exercise.targetWeight || 0, actualReps: Number.parseInt(exercise.reps) || 0 })))
  const [step, setStep] = useState(0)
  const completedCount = results.filter(result => result.completed).length
  const updateResult = (id: string, field: 'completed' | 'actualWeight' | 'actualReps', value: boolean | number) => setResults(current => current.map(result => result.exerciseId === id ? { ...result, [field]: value } : result))
  const exercise = day.exercises[step]
  const result = exercise && results.find(item => item.exerciseId === exercise.id)
  return <div className="client-workout"><div className="client-workout-title"><small>تمرین امروز · {day.title}</small><h1>{exercise ? `حرکت ${faNumber(step + 1)} از ${faNumber(day.exercises.length)}` : 'جلسه بدون حرکت'}</h1><p>{faNumber(completedCount)} حرکت انجام‌شده · حدود {faNumber(day.exercises.length * 9)} دقیقه</p></div><div className="workout-progress"><i style={{ width: `${completedCount / Math.max(1, day.exercises.length) * 100}%` }}/><span>{faNumber(completedCount)} از {faNumber(day.exercises.length)} حرکت</span></div>{exercise && result && <div className="workout-exercises"><article className={result.completed ? 'completed' : ''}><div className="exercise-main"><h3>{exercise.name}</h3><p>{faNumber(exercise.sets)} ست × {exercise.reps} تکرار {exercise.targetWeight ? `· هدف ${exercise.targetWeight.toLocaleString('fa-IR')} کیلو` : ''}</p>{exercise.note && <small>{exercise.note}</small>}<div className="actual-inputs"><label>وزنه واقعی<input type="number" inputMode="decimal" value={result.actualWeight || ''} onChange={e => updateResult(exercise.id, 'actualWeight', Number(e.target.value))}/><span>kg</span></label><label>تکرار واقعی<input type="number" inputMode="numeric" value={result.actualReps || ''} onChange={e => updateResult(exercise.id, 'actualReps', Number(e.target.value))}/></label></div></div></article><button type="button" className="client-primary workout-done" onClick={() => { updateResult(exercise.id, 'completed', !result.completed); if (step < day.exercises.length - 1) setStep(step + 1) }}>{result.completed ? <><Check/> انجام شد · تغییر وضعیت</> : <><Check/> انجام شد</>}</button></div>}<div className="workout-step-actions"><button type="button" disabled={step === 0} onClick={() => setStep(step - 1)}>حرکت قبل</button>{step < day.exercises.length - 1 && <button type="button" onClick={() => setStep(step + 1)}>حرکت بعد</button>}</div><button className="button primary full finish-workout" disabled={!completedCount} onClick={() => review(results)}>پایان و ثبت بازخورد <ArrowLeft size={18}/></button></div>
}
